controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_product_new:
    path: /product/new
    controller: App\Controller\ProductController::new
    methods: [GET, POST]

